#!/bin/sh
#

load_drivers()
{
	while IFS= read -r line; do
		modprobe $line
	done < "/etc/modules-load.myir/$1.conf"
}

do_board()
{
    mkdir -p /root/myir
    mkdir -p /usr/share/myir/
    mkdir -p /home/ftp/log
    mount -o bind /usr/share/myir /root/myir
    chmod -R 777 /root/myir
	load_drivers "am335x" 
}

dmesg -n 5

case "$1" in
	start)
		do_board
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
